### ISSUE TITLE
5.13.19-3-pve dkms error

### ISSUE THREAD

**Issue by FallingSnow** [VGPU-Community-Drivers/Merged-Rust-Drivers#1]
I'm using proxmox 7.1's kernel version `5.13.19-3-pve`.
The dkms build has a lot of errors. Applying the `fourteen.patch` eliminates all these errors except the one below.
I'm not sure how to fix it.

```c
...
  CC [M]  /var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/nvidia-vgpu-vfio.o
  CC [M]  /var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/vgpu-devices.o
  CC [M]  /var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/nv-pci-table.o
  LD [M]  /var/lib/dkms/nvidia/460.73.01/build/nvidia.o
/var/lib/dkms/nvidia/460.73.01/build/nvidia-drm/nvidia-drm-modeset.c: In function ‘__will_generate_flip_event’:
/var/lib/dkms/nvidia/460.73.01/build/nvidia-drm/nvidia-drm-modeset.c:96:23: warning: unused variable ‘primary_plane’ [-Wunused-variable]
   96 |     struct drm_plane *primary_plane = crtc->primary;
      |                       ^~~~~~~~~~~~~
  LD [M]  /var/lib/dkms/nvidia/460.73.01/build/nvidia-modeset.o
/var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/nvidia-vgpu-vfio.c:228:6: error: ‘struct mdev_parent_ops’ has no member named ‘open_device’
  228 |     .open_device      = nv_vgpu_vfio_open,
      |      ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/nvidia-vgpu-vfio.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/vgpu-devices.c: In function ‘nv_vfio_vgpu_get_attach_device’:
/var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/vgpu-devices.c:730:1: warning: the frame size of 1040 bytes is larger than 1024 bytes [-Wframe-larger-than=]
  730 | }
      | ^
/var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/vgpu-devices.c: In function ‘nv_vgpu_dev_ioctl’:
/var/lib/dkms/nvidia/460.73.01/build/nvidia-vgpu-vfio/vgpu-devices.c:357:1: warning: the frame size of 1120 bytes is larger than 1024 bytes [-Wframe-larger-than=]
  357 | }
      | ^
make[1]: *** [Makefile:1879: /var/lib/dkms/nvidia/460.73.01/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.19-3-pve'
make: *** [Makefile:80: modules] Error 2
```

**Comment by FlorianZ** [comment]
You have to undo these two lines of the fourteen.patch: https://github.com/VGPU-Community-Drivers/Merged-Rust-Drivers/blob/02a44e3e15ac39d3b60b82b19207c50e3f650f2e/NVIDIA-Linux-x86_64-460.73.01-grid-vgpu-kvm/kernel/patches/fourteen.patch#L188

The members are .open and .release (as opposed to .open_device and .close_device) in this version of the pve kernel.

**Comment by FlorianZ** [comment]
Oh, and in my case the `libvgpu_unlock_rs.so` that shipped with this driver was built against `glibc` 2.33, but my` 5.13.19-6-pve` came with version 2.31. This prevented both the `nvidia-vgpud` and `nvidia-vgpu-mgr` services from starting up properly.

I bet there are multiple ways to solve this problem, but I just built `vgpu_unlock-rs` as described here: https://github.com/mbilker/vgpu_unlock-rs#readme and then copied the build product .so file to `/usr/lib/nvidia/` replacing the `libvgpu_unlock_rs.so` that shipped with the driver.

**Comment by VGPU-Community-Drivers** [comment]
For proxmox this driver is not recommended - a kvm only driver would be better and more stable - you dont need access from your host server to the gpu, thus merged is not needed. 

The other issue is 'known' unfortunally I can not compile it kn a other way on my system but a recompile of rust unluck and a simple replace of the binary should fix the issue
