### ISSUE TITLE
sixteen.patch is missing from dkms manifest

### ISSUE THREAD

**Issue by FallingSnow** [VGPU-Community-Drivers/Merged-Rust-Drivers#2]
https://github.com/VGPU-Community-Drivers/Merged-Rust-Drivers/blob/2385a3ac781da490385dab043cfbdb2ecec5ac9e/NVIDIA-Linux-x86_64-460.73.01-grid-vgpu-kvm/.manifest#L9-L11

**Comment by VGPU-Community-Drivers** [comment]
Thx for the information was added since then :)
