### ISSUE TITLE
Move NVIDIA-Linux-x86_64-460.73.01-grid-vgpu-kvm.run to release

### ISSUE THREAD

**Issue by MakiseKurisu** [VGPU-Community-Drivers/Merged-Rust-Drivers#4]
Right now git clone is quite slow since a lot of bandwidth was used to download objects related to this file. Moving it out (and a force push to clean up history) can help people to better track this repo.

**Comment by VGPU-Community-Drivers** [comment]
You dont need to clone/pull the hole repi just the run. 
But if you send me a link/pr with the release fix gladly to merge that ;)

**Comment by VGPU-Community-Drivers** [comment]
https://github.com/VGPU-Community-Drivers/Merged-Rust-Drivers/releases/tag/1.0.0
